name: 'gcloud'

env:
  REGION: europe-west10

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: 'actions/checkout@v4' # Must come first!
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCLOUD }}'

      - name: Build Docker image
        run:
          gcloud builds submit --tag gcr.io/ctp-opti-serv/flask-app:v1 .

      - name: Deploy to Cloud Run
        run:
          gcloud run deploy flask-app --image gcr.io/ctp-opti-serv/flask-app:v1--allow-unauthenticated --platform managed --region $REGION
          